### ISSUE TITLE
How is this project rendered?

### ISSUE THREAD

**Issue by Asimoz** [anvaka/word2vec-graph#5]
Hi，this work is so cool! And I am new to data visualization. I try to understand the ngraph. But I am confused about how this project rendered the 3D graph. I could not find pixi, three, webgl or canvas.
Thanks in advance for your commenting! I really like this wonderful graph.

**Comment by anvaka** [comment]
Thank you!

Here is the description of how this project is rendered: https://github.com/anvaka/pm#your-own-graphs

**Comment by Asimoz** [comment]
Thanks！

I was surprised that it could render more than 1,000,000 nodes！Amazing！
